---
name: Enhancement or feature request.
description: File an enhancement/feature request to make Twig more amazing !

body:
  - type: textarea
    attributes:
      label: Description of your enhancement/feature request proposal.
      description: |
        A description of what enhancement and (or) feature request, you'd like to see in Twig.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives.
      description: |
        What other alternatives currently exist that you are employing.
    validations:
      required: true
